### ISSUE TITLE
Support un-flattening

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2068]
Today, "ForMember" only supports top-level properties. This creates the PropertyMap and all its ilk.

I'm proposing un-flattening, by allowing mapping to a path:

```
CreateMap<Foo, Bar>()
    .ForPath(dest => dest.Foo.Bar.Baz, opt => opt.MapFrom(src => src.Boo.Buzz.Bizz));
```

`ForPath` would be new, it would allow any chain of member access expressions. For simplicity, we would not support anything but a chain of member access. No collections, array access, methods etc. Just property/field chains.

The "opt" part would be a new expression interface. We would add new supporting DSL interfaces, configuration gatherers, and Map config objects (PathMap to go along with PropertyMap etc.)

We can limit the creation of these PathMaps to:

- When you call ForPath explicitly
- When you use MemberList.Source in CreateMap (or ReverseMap).

To support full un-flattening (as our users would see it as done):

- [x] Explicit configuration of paths (ForPath) #2074 
- [x] ReverseMap creates PathMaps based on PropertyMaps #2080 
- [x] PreserveReferences on ReverseMap for when we detect maps used in child properties #2124 
~~- [ ] UseDestinationValue (needs more investigation)~~ defer this one

**Comment by lbargaoanu** [comment]
I've started working on this one.

**Comment by lbargaoanu** [comment]
I guess the idea is to create everything on the destination path if it's not already created and skip those without a setter.

**Comment by jbogard** [comment]
@lbargaoanu did #2080 fix the second item in the list?

**Comment by lbargaoanu** [comment]
Yes.

**Comment by jbogard** [comment]
So initially I thought that perhaps MemberList should signal to the typemap factory to decide to be able to unflatten. But perhaps as a first step we ONLY make ReverseMap do unflattening? That would get rid of item number 3. It would also force you to go from Entity -> DTO -> Entity in configuration. They'd be joined at the hip (which might be nice for future work to make that assumption).

**Comment by lbargaoanu** [comment]
I agree, let's start with ReverseMap and see where it goes.

**Comment by lbargaoanu** [comment]
About trying to detect cycles at configuration time.
In some cases PreserveReferences wouldn't help, we would need MaxDepth, but we have no way of knowing that.
If, for some reason, a member is not inlined, we might miss a cycle.
We would need a pass just to detect cycles, before actually bulding the execution plan.
Right? :)

**Comment by jbogard** [comment]
Yeah that almost sounds like a 2-pass compiler.

**Comment by lbargaoanu** [comment]
I think UseDestinationValue would be trivial to implement (just set the value in the property map), but maybe it would be better to wait to see if anybody needs it.

**Comment by jbogard** [comment]
Is the PreserveReferences thing done? I think that's what I meant by that item - circular references.

**Comment by lbargaoanu** [comment]
:) Yes.

**Comment by lbargaoanu** [comment]
@jbogard @belurd I'm not sure whether to revert [this](https://github.com/AutoMapper/AutoMapper/wiki/Reverse-Mapping-and-Unflattening/_compare/ba6788693ef917bdfef2b11ec70266d265931127...5020226a937a76312b9502e9864ce27d60da84f2). It seems misleading because of the default flattening.

**Comment by belurd** [comment]
@lbargaoanu @jbogard I am learning AutoMapper. I have tried to run the examples you have provided for reverse mapping. Couldn't compile few of them at all. I have tried to correct them according to the text in explanations.

**Comment by lbargaoanu** [comment]
The actual tests are [here](https://github.com/AutoMapper/AutoMapper/blob/master/src/UnitTests/ForPath.cs). And I appreciate you fixing the errors, but overall, I'm not sure it's the best result.
