### ISSUE TITLE
Value Transformers

### ISSUE THREAD

**Issue by jbogard** [AutoMapper/AutoMapper#2258]
This is the tracking issue for #1414

Work to be done:

- [x] Transformers at the global level #2261 
- [x] Transformers at the profile level #2261 
- [x] Transformers at the type map level #2261 
- [x] Transformers at the member level #2261 
- [x] Apply transformers to LINQ projection #2324 
- [x] Wiki docs

**Comment by chris-gh** [comment]
Based on  @lbargaoanu 's comments in the commit.

Perhaps the ApplyTransform() needs a second parameter which is an int index and has a default value.

Then stacked transforms are run in this index order first, then in definition/creation order second.

If you want something run first, you give it a very low (negative) number, if you want it run last you give it a high number. If you don't care - then leave it at the default value.

**Comment by jbogard** [comment]
Hrm. I'd rather just expose a list directly.

**Comment by DavidRogersDev** [comment]
I suspect this feature is something I would be interested in. I just upgraded Automapper from 5.1.1 to 6.1.1 and it broke one of my mappings which uses custom resolvers. All I had to do to fix the null was swap the order. So, to:  
  
```configuration.CreateMap<PatientInfoRawDto, PatientInfoModel>()
.ForMember(m => m.PatientId, opt => opt.MapFrom(p => p.patID))
.ForMember(m => m.PatientIdForView,
	opt => opt.ResolveUsing<PatientIdResolver<PatientInfoRawDto, PatientInfoModel>>())
.ForMember(m => m.PatientEpisode,
	opt => opt.ResolveUsing<PatientEpisodeDataResolver<PatientInfoRawDto, PatientInfoModel>, int>(src => src.patID))```
from:
```configuration.CreateMap<PatientInfoRawDto, PatientInfoModel>()
	.ForMember(m => m.PatientId, opt => opt.MapFrom(p => p.patID))
	.ForMember(m => m.PatientEpisode,
		opt => opt.ResolveUsing<PatientEpisodeDataResolver<PatientInfoRawDto, PatientInfoModel>, int>(src => src.patID))
	.ForMember(m => m.PatientIdForView,
		opt => opt.ResolveUsing<PatientIdResolver<PatientInfoRawDto, PatientInfoModel>>())```

To be able to control that ordering would be ideal.
